; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_dir = C:\Users\Marcel\.platformio\builds\HomeSystem
libdeps_dir = C:\Users\Marcel\.platformio\builds\lib

default_envs = 
	debug

[common]
platform = espressif32
board = seeed_xiao_esp32c3
board_build.mcu = esp32c3
framework = arduino
debug_tool = esp-builtin
build_unflags = -std=gnu++11
build_flags = 
	-D VERSION=1.0.0
	-D CORE_DEBUG_LEVEL=5
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
	-std=gnu++14
	-Wall
	-Wextra
	-O2
lib_ldf_mode = chain+
lib_deps = 
	knolleary/PubSubClient@^2.8
	beegee-tokyo/DHT sensor library for ESPx@^1.19

[env:debug]
extends = common
build_type = debug
;debug_tool = esp-prog
;debug_init_break = tbreak setup  ; S'arrête au début du setup()
;upload_protocol = esp-prog ; Essayer aussi de téléverser via JTAG pour tester la chaîne
; Optionnel : Forcer la vitesse du JTAG si vous avez des erreurs de connexion
;debug_speed = 500
; Pour voir les logs série en même temps (via l'interface 1 de l'ESP-Prog)
monitor_speed = 115200

build_flags = 
	${common.build_flags}
	-DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
	-D DEBUG_MODE=1


lib_deps = 
	knolleary/PubSubClient@^2.8
	beegee-tokyo/DHT sensor library for ESPx@^1.19

[env:production]
extends = common
build_type = release
build_flags = ${common.build_flags}
	-DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
lib_deps = 
	knolleary/PubSubClient@^2.8
	beegee-tokyo/DHT sensor library for ESPx@^1.19
